### ISSUE TITLE
prediction 시 looping 문제

### ISSUE THREAD

**Issue by rippertnt** [SKT-AI/KoGPT2#1]
안녕하세요~ 좋은 모델 공개해 주셔서 감사합니다.
설치하여 예제를 돌려보던 중 다음과 같은 문구를 입력해 보았습니다.

"2029년에는, "
을 입력하면 "_그", "_후",","의 단어가 무한 반복됩니다.

이어질 문장을 예측하는것이 잘 되는것이 있는반면, </s> 태그를 만나지 못하고 동일한 말이 반복되는 케이스가 있는것 같습니다. 예외처리를 할수는 있겠지만, 학습시에 방법을 바꾸면 나아질수 있는 문제일지 궁금합니다.

**Comment by haven-jeon** [comment]
아시다시피 특정 상황에서 생성 모델에서의 반복적 생성은 이미 알려진 문제입니다

예제 코드는 가장 간단한 greedy sampling을 하는 코드입니다. 이 이외에 생성을 위한 다양한 파라메터가 존재하니 테스트 해보시길 추천드립니다.



https://huggingface.co/transformers/main_classes/model.html?highlight=generate#transformers.PreTrainedModel.generate
