### ISSUE TITLE
개행 문제

### ISSUE THREAD

**Issue by gyunggyung** [SKT-AI/KoGPT2#12]
안녕하세요. 주어진 정보를 가지고 스스로 문제를 해결해보려고 했지만 실패해서 다시 문의드립니다.

사전의 값을 바꾸고 `.spiece` 파일로 다시 저장하는 것은 어떻게 해야될까요?

google/sentencepiece#485

관련 이슈를 공유드립니다!

감사합니다.

**Comment by haven-jeon** [comment]
`.spiece` 파일을 @gyunggyung 께서 수정하고자 하는 이유는 아직 잘 모르겠습니다. 왜 수정해야 되는건지요? 

추가된 토큰을 기반으로 자동 토큰화를 위해서라면 이해가 가는데, 이는 위험할 수 있다는 이야기는 이미 드렸던거 같습니다. 

자동 토큰화가 아니라면 토크나이저로 토큰 화 이후 스페셜 토큰을 넣는 작업으로 코딩을 하면 될거 같은데, 아닌가요?

굳이 어려운 길을 가지 않아도 쉽게 해결 할 수 있는 방법이 있는 문제 같아서 그렇습니다만...

**Comment by gyunggyung** [comment]
추가된 토큰을 기반으로 자동 토큰화를 위해서가 맞습니다 :) ㅎㅎㅎ 그렇죠 해보고 싶은 욕심도 있는 거 같습니다!! 지금도 말씀해주는 방식으로 코딩을 통해서 진행하고 있는데, `.spiece` 파일을 바꾸는 방법은 딱히 없을까요?

감사합니다!

**Comment by soeque1** [comment]
@gyunggyung 재미로 봐주세요
https://github.com/google/sentencepiece/blob/master/python/sentencepiece_model_pb2.py 파일이 필요합니다.

```
import copy
import sentencepiece_model_pb2 as model
m = model.ModelProto()
m.ParseFromString(open('xx.spiece', 'rb').read())

# >>> m.pieces[0]
# piece: "<s>"
# score: 0.0
# type: CONTROL

# >>> m.pieces[4]
# piece: "<sys>"
# score: 0.0
# type: USER_DEFINED

# >>> m.pieces[135]
# piece: "\355\225\230\352\263\240"
# score: -31.0

```
speical token(CONTROL)과 일반 토큰의 스트럭처가 다릅니다.
https://github.com/google/sentencepiece/blob/master/doc/special_symbols.md


```
sp_tokens = # sp tokens (없으면 생략)

orig_idx = []  # 새로운 sp 토큰과 일반 토큰 

for i in sp_tokens:
    tmp_piece = copy.deepcopy(m.pieces[0])  # 0은 토크나이저 마다 상이
    tmp_piece.piece = i
    orig_idx.append(tmp_piece)

real_vocab = # NEW 토큰들 (없으면 생략)

for i in real_vocab:
    tmp_piece = copy.deepcopy(m.pieces[4]) # 4는 토크나이저 마다 상이
    tmp_piece.score = 0  # score가 보통 음수라서 0으로 주면 우선시 됩니당
    tmp_piece.piece = i
    orig_idx.append(tmp_piece)

for v in orig_idx:
    m.pieces.append(v)

with open('new_xxx.spiece', 'wb') as f:
    f.write(m.SerializeToString())

```

보캡이 증가했기 때문에 Huggingface 이용시
model = XXX.from_pretrained('gpt2')
model.resize_token_embeddings(len(tokenizer)) 

필요합니다.

**Comment by haven-jeon** [comment]
12일이 지났기 때문에 해당 이슈는 없는것으로 판단하고 닫도록 하겠습니다.
