### ISSUE TITLE
사용된 버전 문의

### ISSUE THREAD

**Issue by taeyoung4808** [SKT-AI/KoGPT2#13]
안녕하세요.

사용된 버전 문의드립니다.

readme에 있는 내용대로 인스톨하고 
#2 해당 이슈에 있는 예시를 실행시켜보았는데
eos_token_ids가 지원되지 않는 인자로 나와 확인해보니 eos_token_id로 변경된걸로 확인하였습니다.
변경 후 실행해보니 

RuntimeError: The size of tensor a (3) must match the size of tensor b (12) at non-singleton dimension 0

오류가 발생하고있습니다. 크기가 달라 발생하는문제같은데 혹시 예제에 사용된 
PyTorch 및 transformers 버전을 알 수 있을까요?

**Comment by haven-jeon** [comment]
네.. 그렇군요. 훔..

https://github.com/SKT-AI/KoGPT2/blob/master/requirements.txt 에 나와 있는 최소 버전이 예제 실행시 사용한 버전들입니다. 

한번 해보고시고 이슈 있으시면 알려주세요.

**Comment by taeyoung4808** [comment]
답변 감사합니다.

말씀하신대로 최소버전으로 맞춰서 실행해보니 아래 오류가 발생합니다. 

AttributeError: 'GPT2LMHeadModel' object has no attribute 'generate'

해당버전에서는 generate가 지원이 안되나보네요
맞는버전을 천천히 잘 찾아보겠습니드아.....

**Comment by taeyoung4808** [comment]
바로 확인했습니다~
transformers  2.4.1 버전에서 정상동작합니다 감사합니다 ~!

**Comment by haven-jeon** [comment]
확인해 주셔서 감사합니다. 

requirements도 업데이트 해야겠네요.. ^^
