### ISSUE TITLE
AttributeError: 'GPT2Config' object has no attribute 'output_past'

### ISSUE THREAD

**Issue by yunho0130** [SKT-AI/KoGPT2#14]
Readme.md의 가이드대로 진행하면 최신버전의 transformers에서는 아래의 에러가 납니다. 
 - AttributeError: 'GPT2Config' object has no attribute 'output_past'

requirements.txt파일을 transformers==2.4.1로 해결하였습니다.

**Comment by iamthatian** [comment]
여기 보면 huggingface/transformers#3734 `output_past`에서 `use_cache`로` 바뀐 거 아닌가요?

**Comment by haven-jeon** [comment]
신규버전이 동작할 수 있게 해야 될거 같네요.. 일단 requirements.txt파일을 수정해서 업데이트 하겠습니다. 

감사합니다.

**Comment by yunho0130** [comment]
@haven-jeon 확인 감사합니다. 작은 바램이 있다면 Merge도 되었으면 좋겠습니다. :)

**Comment by haven-jeon** [comment]
머지 되었습니다. 해당 이슈는 클로즈 하겠습니다.
