### ISSUE TITLE
nsmc 파인튜닝시 파라미터 질문

### ISSUE THREAD

**Issue by MiaYangheeKim** [SKT-AI/KoGPT2#16]
안녕하세요.
KoGPT2를 이용하여 NSMC 데이터셋으로 감정분석 파인튜닝을 하려고 합니다.
이 경우 GPT2LMHeadModel이 아닌 GPT2DoubleHeadsModel을 사용하려고 하는데요.
kogpt2model.load_state_dict(torch.load(model_file) 라인에서 
아래와 같은 오류가 발생합니다.

05/11/2020 19:10:56 - WARNING - __main__ -   device: cuda:1, n_gpu: 4
using cached model
using cached model
Traceback (most recent call last):
  File "KoGPT2-finetuning_KoBERT_ver.py", line 50, in <module>
    gpt2_model, vocab = get_pytorch_kogpt2_model()
  File "/home/yanghee/PycharmProjects/KoGPT2/kogpt2/pytorch_kogpt2.py", line 72, in get_pytorch_kogpt2_model
    return get_kogpt2_model(model_path, vocab_path, ctx)
  File "/home/yanghee/PycharmProjects/KoGPT2/kogpt2/pytorch_kogpt2.py", line 77, in get_kogpt2_model
    kogpt2model.load_state_dict(torch.load(model_file))
  File "/home/yanghee/anaconda3/envs/KoGPT2_py36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 845, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for GPT2DoubleHeadsModel:
	Missing key(s) in state_dict: "multiple_choice_head.summary.weight", "multiple_choice_head.summary.bias". 

이는 배포해주신 파라미터 파일이 GPT2LMHeadModel에 맞춰져있기 때문일까요?
KoGPT2로 NSMC 데이터셋에 테스트 하신 결과도 올려주셨는데, 
혹시 어떤식으로 파인튜닝을 하셨는지 알려주시면 감사하겠습니다!

**Comment by haven-jeon** [comment]
테스트 해보진 않았는데, load_state_dict가 아니라 from_pretrained로 로딩하셔야 될듯 합니다. 

그리고 "multiple_choice_head.summary.weight", "multiple_choice_head.summary.bias"는 로딩시 ignore해도 될듯 하네요..

**Comment by MiaYangheeKim** [comment]
> 테스트 해보진 않았는데, load_state_dict가 아니라 from_pretrained로 로딩하셔야 될듯 합니다.
> 
> 그리고 "multiple_choice_head.summary.weight", "multiple_choice_head.summary.bias"는 로딩시 ignore해도 될듯 하네요..

from_pretrained로 로딩할 시 공유해주신 파라미터 파일(.params)이 'pytorch_model.bin', 'tf_model.h5', 혹은 'model.ckpt.index'에 해당하지 않아 로딩이 안되는 것 같습니다.. nsmc 및 paraphrasing detection에 대한 evaluation을 진행하셨을 때 해당 데이터셋에 대한 파인튜닝을 진행하셨을 것 같은데, 그때 LMHeadsModel을 사용하셨나요?

**Comment by haven-jeon** [comment]
LMHeadsModel모델로 진행했습니다. 

[BOS] [token1] [token2] ...... [EOS] [CLS]

위와 같이 출력해서 [CLS]로 분류했습니다.

**Comment by MiaYangheeKim** [comment]
> LMHeadsModel모델로 진행했습니다.
> 
> [BOS] [token1] [token2] ...... [EOS] [CLS]
> 
> 위와 같이 출력해서 [CLS]로 분류했습니다.

감사합니다!
