### ISSUE TITLE
pre-train 코드

### ISSUE THREAD

**Issue by MiaYangheeKim** [SKT-AI/KoGPT2#17]
안녕하세요.
배포해주신 모델을 기반으로 추가학습을 해보고자 하는데 pre-train 코드가 있다면 배우는 입장에서 참고가 많이 될 것 같습니다. 
혹시 배포하신 KoGPT2모델에 대한 Pre-training 코드 공개 계획은 없으신가요..?
답변주시면 감사합니다.

**Comment by haven-jeon** [comment]
오픈 했을 경우 저희 코드에 대한 관리 부담이 가중되는 문제가 있어서 코드 오픈에는 다소 부담을 가지고 있습니다. 다만 huggingface transformers에 관련 example이 있으니 참고하시면 어떨까 합니다. 

https://github.com/huggingface/transformers/blob/master/examples/language-modeling/run_language_modeling.py

감사합니다.

**Comment by MiaYangheeKim** [comment]
> 오픈 했을 경우 저희 코드에 대한 관리 부담이 가중되는 문제가 있어서 코드 오픈에는 다소 부담을 가지고 있습니다. 다만 huggingface transformers에 관련 example이 있으니 참고하시면 어떨까 합니다.
> 
> https://github.com/huggingface/transformers/blob/master/examples/language-modeling/run_language_modeling.py
> 
> 감사합니다.

답변 감사드립니다! :)
