### ISSUE TITLE
KoGPT2 import 시 에러

### ISSUE THREAD

**Issue by shinedstone** [SKT-AI/KoGPT2#19]
안녕하세요.

기초적인 질문일 수도 있는데, KoGPT2를 동작 시키기 위한 환경 셋업이 잘 안되서 질문 드립니다.
Ubuntu 18.04, CUDA 10.2, Python 3.8이 설치되어 있는 환경인데요.

python pip, anaconda virtual env, docker img(https://github.com/Astro36/KoGPT2)
위 3가지를 활용해서 KoGPT2 package 설치 후, 테스트 코드를 실행하면 아래와 같이 import 부분에서 core dumped  되고 있습니다.

from kogpt2.pytorch_kogpt2 import get_pytorch_kogpt2_model
from gluonnlp.data import SentencepieceTokenizer
from kogpt2.utils import get_tokenizer

혹시 해당 패키지를 돌리기위한 환경 제약사항이 있을까요?

**Comment by haven-jeon** [comment]
reproduce할 수 있는 충분한 환경 정보를 알지 못하면 해결 방안을 알려드리기 어려운점 양해 부탁드립니다.

**Comment by haven-jeon** [comment]
이슈 없음으로 판단하고 클로즈하겠습니다.
