### ISSUE TITLE
연속적인 문장 생성에 관한 문의드립니다.

### ISSUE THREAD

**Issue by jeina7** [SKT-AI/KoGPT2#2]
안녕하세요. 모델 사용에 관해 궁금한 점이 있어 문의를 드리게 되었습니다.

일전에 관련 내용에 대해 문의를 드렸었는데, 연속적인 문장 생성을 하기 위해서는 lm explorer 구현과 연관이 되며 \</s>를 적절히 처리하면 된다는 답변을 받았습니다. 이 때 \</s>를 적절히 처리한다는 의미는 구체적으로 어떤 것인지 궁금합니다. 문장이 생성될 때 \</s>가 나오지 않도록  학습을 시키는 것인지, 혹은 \</s>가 10개의 생성 후보에 나오더라도 무시를 하도록 구현하는 것인지, 아니면 다른 방법이 있는건가요?? 

또한, How to use 부분에서 문장을 생성할 때 10개 생성 후보에서 확률이 가장 높은 것을 argmax로 선택해서 생성하기 때문에 특정 input에 대해 항상 같은 문장이 생성되는 것을 확인했습니다. 그렇다면 매번 다른 문장을 생성하도록 하기 위해 랜덤성을 추가해줄 수 있는 부분이 있을까요??

모델 학습을 위한 train 코드도 공개하실 계획이 있으신지도 궁금합니다.

감사합니다!!

**Comment by haven-jeon** [comment]
네. 질문 감사드립니다. 

아래의 코드를 활용하시면 원하시는 방향으로 생성을 시도해보실 수 있지 않을까 합니다. 

``
import torch
from kogpt2.pytorch_kogpt2 import get_pytorch_kogpt2_model
from gluonnlp.data import SentencepieceTokenizer
from kogpt2.utils import get_tokenizer

tok_path = get_tokenizer()
model, vocab = get_pytorch_kogpt2_model()
tok = SentencepieceTokenizer(tok_path)

sent = '2019년 한해를 보내며,'
toked = tok(sent)
sent_cnt = 0

input_ids = torch.tensor([vocab[vocab.bos_token],]  + vocab[toked]).unsqueeze(0)

outputs = model.generate(
        input_ids=input_ids, num_beams=5,
        max_length=100, repetition_penalty=1.2, temperature=1.5, do_sample=True, eos_token_ids=-1, num_return_sequences=3)
for i in range(3): #  3 output sequences were generated
    toked = vocab.to_tokens(outputs[0][i].squeeze().tolist())
    ret = re.sub(r'(<s>|</s>)', '' , ''.join(toked).replace('▁', ' ').strip())
    print('Generated {}: {}'.format(i, ret))
``

> using cached model
using cached model
using cached model
Generated 0:  2019년 한해를 보내며, 그는 한 세대 전에 자신의 인생 설계도에 다시 새기기 시작해, 새로운 세계관이 되겠다고 선언했다. 이 교수는 이어 “‘다름’을 강조하는 것이 정답일 수 없다고 생각했다, 모든 것을 ‘나‘에게서 찾는 것은 잘못된 생각일 때가 많다“면서 “다름을 받아들이는 것 또한 바로 이것을 깨닫는 과정으로 인식되길 기대한다""는 입장을 밝혔다.28일까지 이어지는 부산비엔날레 기간에는 관람객들을 위해 4일간 특별 이벤트를 마련하고 이를 홍보하는 포스터를 보여준다.16옇
Generated 1:  2019년 한해를 보내며, 특히 젊은 사람들이 많이 본 영화가 1순위입니다. '자작경영 금지 정책'은 국내 재벌의 고질적인 문제점을 지적하기 위한 것이다.c 최필주저작권자(조). 메르스·중증질환 대응책 발표 기자회견 가진 최경환 경제부총리,(대전=뉴스1) 장수영 기자 = 14일 오후 대전 유성구 신동강종합운동장에서 열린 새누리당 제1차 국회의원 연찬실 현장 방문 및 국가메르스 대책 수립을 위해 개최된 최경환 부총리 겸 기재부옇
Generated 2:  2019년 한해를 보내며, 모든 것들이 좋은 결과가 되진 않았을 수 있다고 믿고 있어요." 그는 미국내 한국학(특히 한국의학)과의 연구협력 관계를 확대하기 위해 미국 현지에서 한국의학을 교육하도록 하는 정책을 검토 중이다. &lt;미국대학연합&gt;은 지난 2001년부터 한국의학과에 대한 조사를 실시한 뒤 2015학년도 입시부터 지원자들에게 그 같은 입장을 밝힌 바 있다. ? 또 현재 우리나라 학과에 소속된 대학 중 미국과 직접교제를 체결한옇

**Comment by haven-jeon** [comment]
간단한 예시를 올려드립니다. 관련된 옵션을 조절하시면 말씀하셨던 시도를 해보실 수 있을 것으로 봅니다. 

```python
import re
import torch
from kogpt2.pytorch_kogpt2 import get_pytorch_kogpt2_model
from gluonnlp.data import SentencepieceTokenizer
from kogpt2.utils import get_tokenizer

tok_path = get_tokenizer()
model, vocab = get_pytorch_kogpt2_model()
tok = SentencepieceTokenizer(tok_path, 0, 0)

sent = '중국은 북한과의'
toked = tok(sent)
sent_cnt = 0

input_ids = torch.tensor([vocab[vocab.bos_token],]  + vocab[toked]).unsqueeze(0)

outputs = model.generate(
        input_ids=input_ids,
        max_length=80, repetition_penalty=1.2, pad_token_id=3, do_sample=True, eos_token_ids=1, num_return_sequences=3)
for i in range(3): #  3 output sequences were generated
    toked = vocab.to_tokens(outputs[0][i].squeeze().tolist())
    ret = re.sub(r'(<s>|</s>)', '' , ''.join(toked).replace('▁', ' ').strip())
    print('Generated {}: {}'.format(i, ret))

using cached model
using cached model
using cached model
Generated 0:  중국은 북한과의 관계를 개선하면 상호 협력·상호투자와 무역협력 확대, 인민외교 확산 등의 성과를 거둘 수 있다고 보고 있습니다.
Generated 1:  중국은 북한과의 협상을 ‘전략적 목표’로 세우고 있다고 신문은 전했다.
Generated 2:  중국은 북한과의 관계설정을 서두르면서 북한의 핵개발 및 탄도미사일 프로그램은 ‘비핵화의 평화적 이용’이라는 점을 강조하는 강경한 메시지를 전달한 바 있다.
```

참고로 위 코드는 랜덤성을 추가한 코드여서 매번 다른 문장이 생성될 것입니다. 

연속적인 문장 생성은 `max_length`를 충분히 주고 `eos_token_ids`를 fake id로 주면 원하시는 길이만큼 문장이 생성될 것입니다. 

학습 코드 공개에 대해 많은 분들이 여러 말씀들을 주시고 있는데, 아시다시피 large scale LM 학습의 경우 여러 소프트웨어 및 하드웨어 환경에 따른 이슈가 복합적으로 나올 수 있고 그러한 상황에 저희가 충분히 대응할 리소스가 부족한 상황이여서 코드 공개에 다소 부담을 느끼고 있습니다. 이러한 점 이해 부탁드립니다. 
 
감사합니다!

**Comment by jeina7** [comment]
`model.generate()`의 파라미터로 생성 문장 개수를 설정할 수 있군요! 
살펴보니 model이 transformer 패키지로부터 온 것을 찾았습니다. transformer 모델 사용에 관한 메서드들에 대한 구체적인 내용은 https://huggingface.co/transformers/index.html 에서 확인했습니다.
(generate 함수 : https://huggingface.co/transformers/_modules/transformers/modeling_utils.html)

학습 코드 공개에 대한 고민은 많이 있으실 것 같습니다.
많은 리소스가 들어간 모델을 공개해주셔서 많은 도움이 되었습니다. 다시 한 번 감사합니다! ㅎㅎ
