### ISSUE TITLE
링크 깨짐

### ISSUE THREAD

**Issue by songys** [SKT-AI/KoGPT2#21]
한국어 Paraphrase Detection 데이터 링크가 깨져 있는데 못 찾겠습니다.

혹시 링크가 다른 곳에 있다면 연결시키면 좋을 듯합니다.

"멋진 프로젝트"였네요 고생 많으셨습니다.

**Comment by haven-jeon** [comment]
589182bc85a0 

Fix 했습니다. 
감사합니다.
