### ISSUE TITLE
summarization 질문

### ISSUE THREAD

**Issue by Liberator209** [SKT-AI/KoGPT2#22]
안녕하세요,
kogpt2 를 통해 요약을 진행해 보고 싶은데
관련 문서나 도움이 될만한 자료가 있는지 여쭤보고 싶습니다.

**Comment by haven-jeon** [comment]
안녕하세요. 

https://d4mucfpksywv.cloudfront.net/better-language-models/language-models.pdf 페이퍼 3.6절에 대략적인 방법이 나와 있네요.

**Comment by haven-jeon** [comment]
응답이 없어 클로즈 합니다.
