### ISSUE TITLE
Training dataset/Model size 문의

### ISSUE THREAD

**Issue by ksjae** [SKT-AI/KoGPT2#24]
Training dataset을 따로 공개할 계획이 있나요?

그리고, GPT-2 medium/large 이상의 모델 사이즈로 공개할 계획도 있나요?

**Comment by haven-jeon** [comment]
뉴스 등의 training dataset은 직접 수집한 데이터인데, 이 데이터는 별개의 저작권이 있는 데이터라 저희 맘대로 공개가 불가능합니다. 
GPT-2 medium/large 모델은 공개 계획이 없습니다. 

감사합니다.
