### ISSUE TITLE
Is there any published paper describing your work?

### ISSUE THREAD

**Issue by ilya-palachev** [SKT-AI/KoGPT2#25]
Hello,

First of all, thank you for publishing this repository. Is there any published paper describing your work? I mean a paper in some journal or conference proceedings. This information would help to understand your work a lot.

Thanks in advance!

**Comment by haven-jeon** [comment]
In addition to those mentioned in GPT-2 paper, the parts that were conducted while training Korean are specified in README.md.

**Comment by ilya-palachev** [comment]
> In addition to those mentioned in GPT-2 paper, the parts that were conducted while training Korean are specified in README.md.

Thanks!

**Comment by yuntai** [comment]
were datasets built in-house? if so, are you planning to open it? Also, it'd be great if you could describe your training - hardware resource, hyperparams etc.
