### ISSUE TITLE
LDA를 이용한 리포트 생성 관련 문의드립니다

### ISSUE THREAD

**Issue by jisang93** [SKT-AI/KoGPT2#26]
GPT2 모델을 참고하다 궁금한 부분이 생겨 질문드립니다.

현재 GPT2를 이용해 금융 상품 리포트를 생성하는 프로젝트를 진행하고 있습니다.

저희는 LDA로 10가지 단어를 추출해 해당 단어들을 입력했을 때 리포트를 생성하고자 합니다.

모델 파인튜닝을 위해 저희는 뉴스별 LDA를 추출해 뉴스를 결과값으로 학습을 시키고자 했습니다. 여기서 문제가 발생해 질문을 드립니다.

깃허브를 참고했을 때,

![image](https://user-images.githubusercontent.com/67993306/96408321-31dfc700-121e-11eb-9c36-c30ae9b6d0eb.png)
 

해당 부분에서 문서 전체를 data와 라벨로 지정한다고 이해했습니다.

이 부분에서 라벨을 LDA로 추출한 토픽 단어들로 설정한다면, 저희가 구현하고자 하는 결과값을 얻을 수 있을지를 문의드리고자 했습니다.

아직 자연어 처리를 배운지 얼마 시간이 되지 않아 부족한 부분이 많습니다. 이 점을 도와주시면 감사하겠습니다.

해당 프로젝트 Code : https://github.com/Dev-hottae/PINC/blob/master/Data_Analysis/Summarize_KoGPT2.ipynb

긴 메일 시간내서 읽어주셔서 감사합니다. 좋은 하루 되세요:)

**Comment by haven-jeon** [comment]
코드를 보지는 않았지만, GPT-2에서 conditional generation을 위한 transformers API는 없는걸로 알고 있습니다. 
따라서 원하시는 방향대로 진행하기 위해 labels을 주는 방식은 적합하지 않고,  https://github.com/haven-jeon/KoGPT2-chatbot 에서 작성한 모델 입력 방식으로 학습하는게 맞는걸로 보입니다.

**Comment by jisang93** [comment]
답변 감사합니다. 참고해서 진행하겠습니다.
