### ISSUE TITLE
입력 텍스트가 문장인 경우

### ISSUE THREAD

**Issue by MiaYangheeKim** [SKT-AI/KoGPT2#3]
안녕하세요^^
좋은 모델 공개해주셔서 감사드립니다.
KoGPT2 모델을 설치하고 돌려보았는데 한 가지 의문점이 생겨 질문 드립니다.

입력 텍스트를 바꾸어가며 몇 가지 실험을 해보았는데, 입력 텍스트가 문장이 아닌 경우(예: "나는 밥을")에는 다음 토큰들이 정상적으로 생성되지만, 입력 텍스트가 문장인 경우(예: "나는 밥을 먹는다.")에는 다음 토큰이 생성되지 않는 것을 보았습니다.

OpenAI의 GPT2의 경우 문장(혹은 문장들)을 입력으로 넣으면 비슷한 맥락의 문장들이 추가적으로 생성되었는데요. GPT2를 기반으로 한 KoGPT2에서도 이러한 기능이 가능할 것이라 보는데 generate 함수의 파라미터를 바꾸어도 문장에 대한 다음 문장 생성이 이루어지지 않는 것 같아 질문 드립니다. 

이전 질문글에 대한 답변을 참고하여 num_return_sequences 파라미터를 조정해보았지만, 입력 텍스트가 문장의 형태인 경우에는 

Generated 0:  나는 밥을 먹는다.                                                                                      
Generated 1:  나는 밥을 먹는다.                                                                                      
Generated 2:  나는 밥을 먹는다. 

와 같이 되더군요. 
이처럼 입력 텍스트가 문장인 경우 이어서 연속적인 문장이 생성되도록 하려면 모델의 어떤 부분을 조정해야 하는지 알려주신다면 감사하겠습니다!

**Comment by haven-jeon** [comment]
안녕하세요. ^^

먼저 #2 참고하시구요. 

간단하게 아래와 같이 만들어 낼 수 있습니다. 

```python
import torch
from kogpt2.pytorch_kogpt2 import get_pytorch_kogpt2_model
from gluonnlp.data import SentencepieceTokenizer
from kogpt2.utils import get_tokenizer

tok_path = get_tokenizer()
model, vocab = get_pytorch_kogpt2_model()
tok = SentencepieceTokenizer(tok_path, 0, 0)

sent = '나는 밥을 먹는다.'
toked = tok(sent)
sent_cnt = 0

input_ids = torch.tensor([vocab[vocab.bos_token],]  + vocab[toked]).unsqueeze(0)

outputs = model.generate(
        input_ids=input_ids,
        max_length=50, repetition_penalty=1.2, do_sample=True, eos_token_ids=-1, num_return_sequences=3)
for i in range(3): 
    toked = vocab.to_tokens(outputs[0][i].squeeze().tolist())
    ret = re.sub(r'(<s>|</s>)', '' , ''.join(toked).replace('▁', ' ').strip())
    print('Generated {}: {}'.format(i, ret))

using cached model
using cached model
using cached model
Generated 0:  나는 밥을 먹는다. “왜 그걸 다 가르쳐주러 오세요? 그래야 내 말 잘 듣습니다.” 그 말에 기분이 좋다”고 입을 열었다. 이후 노홍철은 “‘라디오스타’는 내가옇
Generated 1:  나는 밥을 먹는다. 그러나 이를 거절한 남성은 곧바로 이마를 손으로 가리키며 '왜 그러냐, 미안하다'고 말했고 이내 그녀의 손에 손을 가져다 댔다. 하지만 이후 남성은 남성을 피해 도망갔고 남성의 뺨이 그의옇
Generated 2:  나는 밥을 먹는다. “다섯 번째 생일이다가 지나가면 저기서 먹을 거 같애요.” 하지만 그는 이렇게 말했다. 그는 ‘우리 가게’라고만 할 수밖에 없는 이유를 물었다. “옇
```

감사합니다!

**Comment by haven-jeon** [comment]
별도 피드백이 없는 관계로 해당 이슈는 클로즈 합니다!

**Comment by MiaYangheeKim** [comment]
eos_token_ids 파라미터를 다른 값으로 변경하는 방법이 있네요. 답변 감사드립니다!
