### ISSUE TITLE
한국어 Paraphrase Detection 데이터를 사용한 Test Accuracy 측정

### ISSUE THREAD

**Issue by imsoncod** [SKT-AI/KoGPT2#32]
한국어 Paraphrase Detection 데이터를 사용한 Test Accuracy 를 측정하는 코드를 공유해주실수 있으신가요?

**Comment by haven-jeon** [comment]
GPT-1 Paper 에 파인튜닝 아키텍처가 있고 그에 따라 진행했습니다. 
코드는 틈이 날때 올려드리도록 하겠습니다.

**Comment by imsoncod** [comment]
@haven-jeon 알겠습니다 감사합니다 :)

**Comment by haven-jeon** [comment]
https://github.com/SKT-AI/KoGPT2#examples 에 KorSTS 코드 링크 올려두었으니 참고하시기 바랍니다.
