### ISSUE TITLE
Korean Wiki 출처 문의

### ISSUE THREAD

**Issue by youneon** [SKT-AI/KoGPT2#33]
Korean Wiki 와 Other corpus의 각각 출처가 궁금합니다.

**Comment by haven-jeon** [comment]
한국어 위키 : https://ko.wikipedia.org/wiki/%ED%95%9C%EA%B5%AD%EC%96%B4_%EC%9C%84%ED%82%A4%EB%B0%B1%EA%B3%BC

Other corpus의 상세 내용 공개는 내부 논의가 필요해서 바로 말씀드리기 어려울거 같습니다.
양해 부탁드립니다.

**Comment by haven-jeon** [comment]
더 이상 드릴 말씀이 없기 때문에 close하겠습니다.
