### ISSUE TITLE
KoGPT2를 이용한 fine-tuning을 진행 하고 싶습니다.

### ISSUE THREAD

**Issue by Yongyong-k** [SKT-AI/KoGPT2#34]
안녕하세요. 공부중인 학부생입니다.

올려주신 KoGPT2 이전 모델을 보고 공부를 하다 오픈소스가 제공 중지 되었어서 계속 제자리 걸음을 걷고 있었습니다.

그러던 도중에 koGPT2-v2를 올리신 것을 확인하였습니다.

혹시 fine-tuning을 할 수 있는 방법이나, 오픈소스를 공유 받을 수 있을까요??

**Comment by haven-jeon** [comment]
https://github.com/SKT-AI/KoGPT2#examples 에 정리하고 있습니다. 
일단 chit chat 예제가 v2 적용되어 있습니다.

**Comment by Yongyong-k** [comment]
감사합니다. 하지만 저는 소설 데이터 셋으로 트레이닝을 하려고 합니다. 
챗봇 예제 보며 공부하고 있겠습니다.

**Comment by haven-jeon** [comment]
https://github.com/SKT-AI/KoGPT2#examples 에 서브테스크 코드 링크 올려두었으니 참고하세요.

**Comment by Yongyong-k** [comment]
정말 감사합니다 더 공부 해보겠습니다

**Comment by haven-jeon** [comment]
해당 이슈는 클로즈 하겠습니다.

**Comment by haven-jeon** [comment]
https://github.com/haven-jeon/KoGPT2-subtasks 확인 부탁드립니다.
