### ISSUE TITLE
gpt2 v2 fine tuning

### ISSUE THREAD

**Issue by dodoyeon** [SKT-AI/KoGPT2#38]
현재 소설 데이터셋을 이용해 gpt2 를 학습시키려고 하는 학생입니다.

fine tuning 을 하려고 하는데 
kogpt2 = GPT2LMHeadModel.from_pretrained('skt/kogpt2-base-v2')

이 코드의 "skt/kogpt2-base-v2"  부분에서 에러가 발생합니다
OSError: Model name 'skt/kogpt2-base-v2' was not found in model name list. We assumed '[https://s3.amazonaws.com/models.huggingface.co/bert/skt/kogpt2-base-v2/config.json](https://s3.amazonaws.com/models.huggingface.co/bert/skt/kogpt2-base-v2/config.json)' was a path, a model identifier, or url to a configuration file named config.json or a directory containing such a file but couldn't find any such file at this path or url.

혹시 어떤 문제인지 여쭤봐도 될까요?

**Comment by haven-jeon** [comment]
안타깝지만 에러를 재현하기 어렵습니다. 

아래 코드 잘 동작합니다. 

```python
from transformers import GPT2LMHeadModel

mdl = GPT2LMHeadModel.from_pretrained('skt/kogpt2-base-v2')
mdl.config
```

위 에러 메시지 보니 경로가 좀 이상하네요. `https://s3.amazonaws.com/models.huggingface.co/bert/skt/kogpt2-base-v2/config.json` bert가 중간에 왜 있을까요?

**Comment by haven-jeon** [comment]
별도 응답이 없어 해당 이슈 클로즈 합니다.

**Comment by dodoyeon** [comment]
지금 현재 transformers 라이브러리 버전을 2.4.1을 사용하고 있는데 최신버전으로 upgrade하였더니 해결하였습니다
감사합니다
