### ISSUE TITLE
 RuntimeError: The size of tensor a (1024) must match the size of tensor b (2459) at non-singleton dimension 3

### ISSUE THREAD

**Issue by Yongyong-k** [SKT-AI/KoGPT2#39]
kogpt2-v2를 파인튜닝 하는 중에 위와 같은 오류가 도출 되었습니다.

혹시 해결책을 알 수 있을까요?? 
![image](https://user-images.githubusercontent.com/75108580/119021882-e91e0580-b9da-11eb-9317-e68a6fe10839.png)

**Comment by haven-jeon** [comment]
아래 파인튜닝 코드를 참고하셔서 코드 개선을 하시길 추천드립니다. 

https://github.com/haven-jeon/KoGPT2-subtasks

**Comment by Yongyong-k** [comment]
예제 참고하면서 만든 코드입니다 ㅠㅠ 나레이티브 예제와 서브테스크 예제 참고 했습니다
https://github.com/shbictai/narrativeKoGPT2

**Comment by haven-jeon** [comment]
네.. 수고하셨습니다. ^^

**Comment by haven-jeon** [comment]
다른 코멘트가 없어 해당 이슈는 클로즈 하겠습니다.
