### ISSUE TITLE
KoGPT2 fine tuning 하는 방법

### ISSUE THREAD

**Issue by curieuxjy** [SKT-AI/KoGPT2#4]
안녕하세요 :)
KoGPT2 fine tuning 하는 방법에 대해 질문 드립니다.
예제 코드에서는 pre-trained 모델의 parameter로 model.eval()하는 것만 나와있는데
model.train()으로 fine tuning하는 code는 어떤 식으로 작성해야 하는지 toy code 부탁드립니다.
감사합니다.

**Comment by haven-jeon** [comment]
네 안녕하세요.

조금만 검색 해보시면 GPT2를 파인튜닝하는 방법을 찾아볼 수 있습니다.
QA에 대한 파인튜닝은 아래 repo에 있네요. 

https://github.com/ftarlaci/GPT2sQA

감사합니다!

**Comment by haven-jeon** [comment]
해당 이슈는 클로즈 하겠습니다.
