### ISSUE TITLE
kogpt2-v2의 generate 함수를 공유 받을 수 있을까요??

### ISSUE THREAD

**Issue by Yongyong-k** [SKT-AI/KoGPT2#42]
파인튜닝 후 문장을 작성 할 때 kogpt2-v2의 generate 함수를 인용하고 싶습니다. 공유 가능할까요?? 잦은 이슈 죄송합니다.

**Comment by haven-jeon** [comment]
https://github.com/SKT-AI/KoGPT2#model

보시면 `generate()` 함수 사용하는 방법을 확인하실 수 있습니다.
