### ISSUE TITLE
model tokenize (vocab_size) 관련 질문 사항

### ISSUE THREAD

**Issue by dodoyeon** [SKT-AI/KoGPT2#43]
사전의 크기가 51,200라고 하셨는데 모델 받은 config가 52,003 이어서 여쭤보고 싶은것이 있습니다.
혹시 vocab size가 모델 parameter에 영향을 주나요?
아니면 tokenizer level 에서만 영향이 있고 모델은 어떤 vocab사이즈여도 상관없나요?

감사합니다

**Comment by haven-jeon** [comment]
네.. vocab size가 달라지면 embedding 측 파라메터 수가 달라지기 때문에 모델 사이즈에 영향을 주게 됩니다.

**Comment by dodoyeon** [comment]
그럼 혹시 사전의 크기는 51,200 인데 실 config의 임베딩 사이즈는 52003 인 이유를 여쭤봐도 될까요?

**Comment by haven-jeon** [comment]
config에는 임베딩 사이즈 정보가 없습니다. 

https://huggingface.co/skt/kogpt2-base-v2/blob/main/config.json

참고하세요. 

https://github.com/huggingface/transformers/blob/daf0d6a97bb0225a2571a2612b8285e2c3913992/src/transformers/models/gpt2/modeling_gpt2.py#L579

**Comment by dodoyeon** [comment]
알려주셔서 감사합니다
참고하겠습니다.
