### ISSUE TITLE
Huggingface transformer: unable to load weights 이슈

### ISSUE THREAD

**Issue by puzzlecollector** [SKT-AI/KoGPT2#44]
안녕하세요 KoGPT2를 이용해서 실험을 해보려고하는 학생입니다. 

Readme.md에 있는 예제 코드 

`model = GPT2LMHeadModel.from_pretrained('skt/kogpt2-base-v2')
`
를 실행하면 Unable to load weights from pytorch checkpoint file for 'skt/kogpt2-base-v2' 라는 에러가 뜨는데 KoGPT2가 더이상 공개 되어있지 않은건가요?

**Comment by haven-jeon** [comment]
https://huggingface.co/skt/kogpt2-base-v2 에서 접근 가능한 상황으로 확인 되어 잘 공개되어 있는걸로 보입니다.

**Comment by haven-jeon** [comment]
![image](https://user-images.githubusercontent.com/957840/126019306-1cd2b101-e18f-4353-b506-27ca000e211a.png)

테스트 해보니 위와 같이 잘 동작합니다. 해당 이슈는 클로즈 하겠습니다.

**Comment by puzzlecollector** [comment]
넵 torch version이 outdated 되어서 그런 것 같네요 (사용하고 있던게 torch 1.4였습니다)
