### ISSUE TITLE
KoGPT2 FineTuning 예제 또는 방법

### ISSUE THREAD

**Issue by lookuss** [SKT-AI/KoGPT2#45]
KoGPT로 파인 튜닝 공부하고 있는 학생입니다. 혹시 파인 튜닝 예제나 방법 정리 되어 있는 글이 있을까요..? 다른 예제 확인 해보는데 
from transformers.configuration_gpt2 import GPT2Config
ModuleNotFoundError: No module named 'transformers.configuration_gpt2'
같은 오류가 발생해서 해결하는데 고생 하고 있네요

**Comment by haven-jeon** [comment]
README에 있던 예제들을 삭제하였는데, 이전 커밋을 참고하시면 될거 같습니다.  https://github.com/SKT-AI/KoGPT2/tree/3b3cbb79caed1ad8230ce6cb4b0cede94b353ec8#user-contributed-examples

**Comment by lookuss** [comment]
혹시 위와 같은 에러 관련 내용은 모르실까요..?

**Comment by lookuss** [comment]
해당 문제는 해결했는데  혹시 지금 깃허브에 있는 버전으로 글작성 되는 어체만 바꾸려고 해도 finetuning으로 해야 할까요..? 어렵네요...ㅎ

**Comment by haven-jeon** [comment]
어체 역시 파인튜닝이 필요합니다.

**Comment by woongchan789** [comment]
> KoGPT로 파인 튜닝 공부하고 있는 학생입니다. 혹시 파인 튜닝 예제나 방법 정리 되어 있는 글이 있을까요..? 다른 예제 확인 해보는데 from transformers.configuration_gpt2 import GPT2Config ModuleNotFoundError: No module named 'transformers.configuration_gpt2' 같은 오류가 발생해서 해결하는데 고생 하고 있네요

안녕하세요. KoGPT2로 파인 튜닝 공부하고 있는 학생인데 혹시 해당 오류를 어떻게 해결하셨는지 여쭤봐도 될까요..? 똑같은 문제로 고생하고 있는데 해결방법을 마땅히 찾지 못했습니다.. 미리 답변에 감사드립니다!

**Comment by lookuss** [comment]
> > KoGPT로 파인 튜닝 공부하고 있는 학생입니다. 혹시 파인 튜닝 예제나 방법 정리 되어 있는 글이 있을까요..? 다른 예제 확인 해보는데 from transformers.configuration_gpt2 import GPT2Config ModuleNotFoundError: No module named 'transformers.configuration_gpt2' 같은 오류가 발생해서 해결하는데 고생 하고 있네요
> 
> 안녕하세요. KoGPT2로 파인 튜닝 공부하고 있는 학생인데 혹시 해당 오류를 어떻게 해결하셨는지 여쭤봐도 될까요..? 똑같은 문제로 고생하고 있는데 해결방법을 마땅히 찾지 못했습니다.. 미리 답변에 감사드립니다!
@woongchan789  많이 늦었지만 ykm990625@gmail.com 으로 연락주시면 제가 알고 있는 부분 연락 드리겠습니다~
