### ISSUE TITLE
Model checkpoint 저장 위치

### ISSUE THREAD

**Issue by sam351** [SKT-AI/KoGPT2#46]
안녕하세요, `KoGPT2`를 fine-tuning하는 실습을 하고자 합니다.
본 repo에는 model checkpoint가 없는 것 같은데, 모델을 사용하려면 `HuggingFace` 에 올라온 파일을 사용하는 방법밖에는 없는 걸까요?
원래 repo에 올라왔던 파일이 현재 `HuggingFace`에 올라간 모델과 동일한 것이 맞나요?

감사합니다

**Comment by haven-jeon** [comment]
README.md에 있는것 처럼 `PreTrainedTokenizerFast.from_pretrained("skt/kogpt2-base-v2",...)` 와 같이 호출하면 huggingface.co에 있는 모델이 자동으로 다운로딩 됩니다.  그러니 HuggingFace 쪽 보셔도 동일한 모델입니다.

**Comment by haven-jeon** [comment]
다른 코멘트가 없어 해당 이슈 클로즈 합니다.
