### ISSUE TITLE
KoGPT2 단어 여러개 넣는 방법

### ISSUE THREAD

**Issue by Rimririn** [SKT-AI/KoGPT2#47]
KoGPT에 제가 원하는 단어 여러개를 넣어서 그 단어들을 포함한 문장을 만드는 방법이 혹시 있을까요?

**Comment by haven-jeon** [comment]
해당 task는 KoGPT2 모델만으로는 어렵구요. KoGPT2 파인튜닝을 통해서 가능할 것으로 보입니다.

**Comment by haven-jeon** [comment]
현재 데모 링크가 고장나 있는데 http://3.36.123.253:7876/ 에서 테스트 가능합니다. 

아래와 같은 하나의 단어를 포함한 문장은 KoGPT2도 다소 생성 가능하나, 단어 여러개는 zero-shot으로는 어려워 보입니다.  하지만 좀 더 큰 모델은 가능한 것으로 보이긴 하네요..

`감사 -> 정말 감사합니다. 영어 -> 한국어보다 영어를 잘 합니다. 사과 -> 사과로 잼을 만들면 맛있지요. 브로콜리 -> 블로콜리는 반찬으로 최고죠. 남자 -> 여자도 좋아하고 남자들도 좋아하는 남녀노소 누구나 즐길 수 있는 메뉴입니다.....`

**Comment by haven-jeon** [comment]
해당 이슈는 클로즈 하겠습니다.
