### ISSUE TITLE
checkpoint/pytorch_kogpt2_676e9bcfa7.params Error

### ISSUE THREAD

**Issue by healthcabbage** [SKT-AI/KoGPT2#48]
Kogpt2 파인튜닝 예제파일을 학습중에 
Invalid URL 'checkpoint/pytorch_kogpt2_676e9bcfa7.params': No schema supplied.
이 오류가 생겨났습니다. 

찾아보니 Kogpt2 파일에서 utils.py 코드 부분에서
tokenizer = {
    'url':'https://pypi.org/project/kogpt2-transformers/',
    'fname':'kogpt2_news_wiki_ko_cased_818bfa919d.spiece',
    'chksum':'818bfa919d'
}

 여기 url 부분에서 오류가 났습니다. 이 오류에 해결방안이 없을까요?

**Comment by haven-jeon** [comment]
코드 조각을 보니 https://github.com/taeminlee/KoGPT2-Transformers 에서 wrapping한 모델 같습니다. https://github.com/taeminlee/KoGPT2-Transformers/issues 에  문의하시는게 적합해 보입니다. 

감사합니다.

**Comment by healthcabbage** [comment]
죄송합니다. 제가 실수로 다른 걸로 수정한 코드를 첨부했습니다. 

예제로 들고온 코드에서는
tokenizer = {
    'url':
 'https://kobert.blob.core.windows.net/models/kogpt2/tokenizer/kogpt2_news_wiki_ko_cased_818bfa919d.spiece',
    'fname': 'kogpt2_news_wiki_ko_cased_818bfa919d.spiece',
    'chksum': '818bfa919d'
}

이 부분에서 url이 오류가 났습니다.

**Comment by haven-jeon** [comment]
위 코드는 현제 레포에서 제공하지 않는 outdate된 코드 입니다. 해당 코드에 대한 동작 여부는 보장하기 어려운점 양해 부탁드릴께요.

**Comment by healthcabbage** [comment]
친절한 답변감사합니다. 궁금한게 해결됬습니다.
