### ISSUE TITLE
KoGPT2를 이용한 Fine-Tuning 성능을 올리고 싶습니다.

### ISSUE THREAD

**Issue by Seyoung-Jung** [SKT-AI/KoGPT2#49]
안녕하세요, KoGPT2로 동화 생성을 해보고자 Fine-Tuning을 해보고 있는 학부생입니다.
우선 좋은 모델을 공개해주셔서 감사합니다. 깃헙을 레퍼런스 삼아 공부하며 개발 중입니다.

질문으로 Fine-Tuning(Transfer Learning)의 성능을 높이는 방법에 대해 자문을 구하고 싶습니다.
제가 목표하고 있는 결과물은 한 문장을 넣었을 때 3가지 문장을 생성하고, 그 중에 하나를 골라 다시 input으로 넣어주면서 문장이 이어지게 동화를 생성하는 것입니다. 현재 KoGPT2에다 별다른 모델 Architecture 추가 없이 동화 데이터로 Transfer learning을 진행해보았는데요, 데이터는 약 650개의 동화를 한 문장씩 Dataset에 넣어 약 36,000개의 문장을 넣었습니다. 해당 결과를 아래 이미지로 첨부했습니다.
하지만 문장이 말이 되지 않는 경우가 대다수입니다. 이를 해결하기 위해 LSTM의 Cell state 역할을 하는 memory 구조를 추가한 모델도 시도해보았으나 성과가 없었습니다.

기본 Transfer Learning을 할 때 Epoch=30으로 해주었는데,(현재 100번으로 시도 중입니다.) 세부 하이퍼파라미터를 튜닝한다고 크게 달라지지 않을 것 같아 자문을 구하고자 합니다. 데이터가 너무 적은 것이 문제일까요? 저의 task에 유의미할만한 검증된 모델이 있을까요? 명확한 답변이 어려우시겠지만 의견 한 번만 주시면 감사하겠습니다 :)

![image](https://user-images.githubusercontent.com/55081331/139379222-02ff4e87-7f0d-4545-b5b9-dfaf44023f47.png)

**Comment by seawavve** [comment]
안녕하세요. 흥미로운 주제라서 계속 보고싶네요. 혹시 repository를 만들어서 공유해주실 수 있을까요?

**Comment by haven-jeon** [comment]
답변이 늦었습니다. ^^;;

재미있는 시도를 하고 계시는거 같습니다. 

일단 간단한 예제를 올려드릴께요.. 

prefix를 좀더 상세하게 주어지면 좀더 원하는 방향으로 문장을 생성할 수 있습니다. 

예를 들어 아래와 같이 말이죠. 

```python
>>> text = '소녀가 주인공인 슬픈 동화를 쓰고 있습니다::  옛날에 한소녀가 살고 있었어요.'
>>> input_ids = tokenizer.encode(text)
>>> gen_ids = model.generate(torch.tensor([input_ids]),
...                            max_length=128,
...                            repetition_penalty=2.0,
...                            pad_token_id=tokenizer.pad_token_id,
...                            eos_token_id=tokenizer.eos_token_id,
...                            bos_token_id=tokenizer.bos_token_id,
...                            use_cache=True)
>>> generated = tokenizer.decode(gen_ids[0,:].tolist())
>>> print(generated)
소녀가 주인공인 슬픈 동화를 쓰고 있습니다::  옛날에 한소녀가 살고 있었어요."
"그런데 그게 무슨 소리야? 너는 왜 이렇게 울고 있는 거니?
한소녀에게 말을 걸면 "너희들은 어떻게 된 거지!"라고 대답하는 것이죠.
이렇게 말하는 한 소녀는,
'아무것도 아니야, 이거.'
하고 말했습니다.
그러자 그녀는 갑자기 눈물을 흘렸어요.
그리고 다시 눈을 감았지요.
눈물이 쏟아지는 것을 보고 난 후, 나는 그녀의 눈물에 대해 이야기하기 시작했어요.`
```

**Comment by haven-jeon** [comment]
별다른 피드백이 없어 해당 이슈는 클로즈 합니다.

**Comment by dodoyeon** [comment]
안녕하세요 조금 늦게 여쭤보고 싶은게 있습니다. 
비슷한 테스크를 하고있는데 혹시 "prefix 를 좀 더 상세하게 주어지면" 이 어떤 의미인지 여쭤봐도 될까요?
감사합니다

**Comment by sappho192** [comment]
> 안녕하세요 조금 늦게 여쭤보고 싶은게 있습니다. 비슷한 테스크를 하고있는데 혹시 "prefix 를 좀 더 상세하게 주어지면" 이 어떤 의미인지 여쭤봐도 될까요? 감사합니다

@dodoyeon 아마도 첫 입력 문장에 맥락을 담은 문장을 덧붙이라는 말씀으로 보입니다. @dodoyeon 님께서 처음에 입력했던 문장은 `옛날에 한 소녀가 살고 있었어요.'`이지만,  답변에 있는 첫 문장은 `소녀가 주인공인 슬픈 동화를 쓰고 있습니다::  옛날에 한 소녀가 살고 있었어요.`으로, "소녀가 주인공인 슬픈 동화를 쓰고 있습니다:: "가 앞에 붙어있거든요.
